Document restrictions for the jvmtiVerboseGCSubscriber event
eclipse-openj9/openj9-docs pull request #1094
Opened 2023-05-03 17:47 UTC by gacholio

Document the fact that these events run under the same restrictions as the GarbageCollectionStart/End events.

2023-05-03 17:48 UTC, gacholio commented
Note that these restrictions have always been in place but not properly documented.

2023-05-03 18:04 UTC, amicic commented
looks good to me
@pshipton

2023-05-04 11:36 UTC, Sreekala-Gopakumar requested changes
1. Change "This function executes..." to "This function runs..."
2. We have mentioned restrictions same as `GarbageCollectionStart` and `GarbageCollectionFinish` but in our existing documents these events or the restrictions are not mentioned. We should add either the content related to that or add a link to any document where these events and the restrictions are mentioned.

2023-05-04 11:39 UTC, gacholio commented
The start and finish events are from the Oracle JVMTI specification. There is no link I know about that isn't specific to a particular JDK version. Do we want to link to Oracle documentation at all?

2023-05-04 11:42 UTC, gacholio commented
Comment 1 addressed.

2023-05-04 11:47 UTC, gacholio commented
Here is a version of the specification for the events: https://docs.oracle.com/en/java/javase/20/docs/specs/jvmti.html#GarbageCollectionStart

2023-05-04 11:51 UTC, gacholio commented
The relevant portion is:
```
This event is sent while the VM is still stopped, thus the event handler must not use JNI functions and must not use JVM TI functions except those which specifically allow such use (see the raw monitor, memory management, and environment local storage functions). 
```
It would be difficult to paraphrase this without excluding critical information.

2023-05-04 12:19 UTC, doveye commented
Linking to Oracle docs is fine, and such links already exist in this topic (in fact I think the doc you found is better than the existing link!) This text is in a section that is about the OpenJ9 extensions so we do need to clarify that it's talking about something that isn't OpenJ9-specific. I suggest something like:

> This function runs under the same restrictions as the `GarbageCollectionStart` and `GarbageCollectionFinish` events in the standard JVMTI specification. For more information about these events, see the [JVMTI Event Index](https://docs.oracle.com/en/java/javase/20/docs/specs/jvmti.html#EventIndex) for your OpenJDK version.

2023-05-04 12:24 UTC, gacholio commented
Thank you, I have made the suggested change.

2023-05-04 14:35 UTC, doveye commented
@gacholio Sorry, but can you please use the Markdown syntax for the link (technically, I think HTML will work but it's unnecessary) and put ` around the event names to highlight them in the normal text. ie 

```
This function runs under the same restrictions as the `GarbageCollectionStart` and `GarbageCollectionFinish` events in the standard JVMTI specification. For more information about these events, see the [JVMTI Event Index](https://docs.oracle.com/en/java/javase/20/docs/specs/jvmti.html#EventIndex) for your OpenJDK version.
```

Thanks!

2023-05-05 00:51 UTC, gacholio commented
Done.

2023-05-09 10:32 UTC, merged

2023-05-09 10:32 UTC, doveye commented
Thanks 🙂 . All merged now.