Remove jdk20 api doc and add jdk21
eclipse-openj9/openj9-docs pull request #1153
Opened 2023-08-29 17:24 UTC by pshipton

The jdk21 doc is created from the head stream and will be updated when it's time for the initial jdk21 release.

https://openj9-jenkins.osuosl.org/job/Build_JDK21_x86-64_linux_Personal/26/

2023-08-29 17:24 UTC, pshipton commented
jenkins doc stage

2023-08-29 19:31 UTC, keithc-ca commented
It seems premature to me to be removing API doc for jdk20 before its replacement (jdk21) is available.

2023-08-29 19:49 UTC, pshipton commented
If merged this will go into the draft docs, not the live docs. The draft docs will only go live at the time of the 0.41 release, at which time jdk20 is out of support.

2023-08-29 20:32 UTC, keithc-ca requested changes

2023-08-29 20:32 UTC, keithc-ca commented on docs/api-jdk21.md
> +# OpenJ9 JDK 20 API documentation
This should say "21" instead of "20".

2023-08-30 00:13 UTC, pshipton commented on docs/api-jdk21.md
> +# OpenJ9 JDK 20 API documentation
Updated.

2023-08-30 02:00 UTC, keithc-ca approved these changes

2023-08-30 02:01 UTC, merged