Add new crypto services for CRIUSec provider
eclipse-openj9/openj9-docs pull request #1259
Opened 2024-01-23 15:11 UTC by Sreekala-Gopakumar

https://github.com/eclipse-openj9/openj9-docs/issues/1249

Added the new crypto services for CRIUSec provider.

Closes #1249
Signed-off-by: Sreekala Gopakumar <sreekala.gopakumar@ibm.com>

2024-01-23 15:14 UTC, Sreekala-Gopakumar commented
Jenkins doc stage

2024-01-23 16:40 UTC, Sreekala-Gopakumar commented
@WilburZjh - I have added the information. Please check and confirm. Thanks!

2024-01-23 18:51 UTC, WilburZjh requested changes

2024-01-23 18:51 UTC, WilburZjh commented on docs/criusupport.md
> +
I think we can update the content from line 37 - 41 by the following
```
MessageDigest: MD5, SHA-1 and SHA-256
SecureRandon
MAC: HmacSHA256
```

2024-01-24 03:04 UTC, Sreekala-Gopakumar commented
Jenkins doc stage

2024-01-24 03:05 UTC, Sreekala-Gopakumar commented
@WilburZjh - I have made the changes. Please check and confirm. Thanks!

2024-01-25 01:16 UTC, WilburZjh commented
LGTM

@katonica FYI

2024-01-25 17:55 UTC, Sreekala-Gopakumar commented
@pshipton - If you are ok with the change, could you please merge this. Thanks!

2024-01-25 21:44 UTC, pshipton approved these changes

2024-01-25 21:44 UTC, merged