Editorial updates to diagnostic topics
eclipse-openj9/openj9-docs pull request #789
Opened 2021-05-12 14:52 UTC by SueChaplain

- fix markdown markup issues
- Add improved links between topics

Signed-off-by: SueChaplain <Sue_chaplain@uk.ibm.com>

2021-05-12 14:52 UTC, SueChaplain commented
Jenkins doc stage

2021-05-12 15:46 UTC, SueChaplain commented
Jenkins doc stage

2021-05-13 13:00 UTC, doveye requested changes
Just one thing that needs fixing.

2021-05-13 13:24 UTC, SueChaplain commented on docs/tool_jdmpview.md
Hmm ... that'll be the `>` ... I didn't spot that for some reason. Trying something else to reformat.

2021-05-13 13:24 UTC, SueChaplain commented
Jenkins doc stage

2021-05-13 14:05 UTC, SueChaplain commented
Jenkins doc stage

2021-05-13 16:50 UTC, SueChaplain commented on docs/tool_jdmpview.md
With the `>` in there I could not get the build to understand that this was a code block, so I pulled out the `info` command into the preceding sentence and now the rest shows as a code block ok. Think this works.

2021-05-17 07:19 UTC, doveye commented on docs/tool_jdmpview.md
Unfortunately the 4 lines of the first example are now wrapped together. Did the 3-apostrophes thing not work?

2021-05-17 08:10 UTC, SueChaplain commented
Jenkins doc stage

2021-05-17 16:24 UTC, AdamBrousseau commented
jenkins doc stage

2021-05-17 16:35 UTC, AdamBrousseau commented
jenkins build container

2021-05-18 08:33 UTC, SueChaplain commented
Jenkins doc stage

2021-05-18 09:20 UTC, merged