AIX 11.0.16 requires the 16.1 XL C++ Runtime
eclipse-openj9/openj9-docs pull request #933
Opened 2022-05-10 13:25 UTC by pshipton

Issue https://github.com/eclipse-openj9/openj9-docs/issues/932

2022-05-10 13:26 UTC, pshipton commented
jenkins doc stage

2022-05-10 15:17 UTC, doveye requested changes

2022-05-10 15:17 UTC, doveye commented on docs/version0.33.md
> +
There's a mismatch between the link further up the topic and the title of this section, so the link doesn't work. But I think the words could use tweaking anyway to clarify that this is a change in level, to be more consistent with the text in the supported env topic, and to use a more official name for the runtime (which also clarifies that it's a third-party thing). Suggest something like:

> **Later level of XL C++ Runtime required on AIX**
> 
> AIX OpenJ9 builds now require version 16.1 of the IBM XL C++ Runtime for AIX (the previous required level was 13.1.3). This later level is required to accommodate a security update to the HarfBuzz text shaping library.

I also found this topic that mentions XL C++: https://eclipse-openj9.github.io/openj9-docs/configuring/#setting-resource-limits-aix-linux-and-macos. Looks like the Java 14 icon and text needs changing to 11.

2022-05-10 16:21 UTC, pshipton commented
jenkins doc stage

2022-05-10 16:34 UTC, pshipton commented
jenkins doc stage

2022-05-10 17:25 UTC, pshipton commented
jenkins doc stage

2022-05-10 17:46 UTC, pshipton commented
jenkins doc stage

2022-05-11 21:30 UTC, pshipton commented
@doveye this is ready for another review.

2022-05-12 13:11 UTC, doveye approved these changes
LGTM

2022-05-12 13:11 UTC, doveye commented on docs/version0.33.md
> +
Ok, I saw the change in levels in the build env table but I guess that's different.

2022-05-12 13:12 UTC, doveye commented
Had to prioritise other things yesterday. Checked again today though and the changes look good, thanks.

2022-05-12 13:12 UTC, merged